# Generated by Django 4.2.25 on 2025-11-05 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interviewsession_created_at_scoreresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questions',
            field=models.JSONField(),
        ),
    ]
