# Generated by Django 5.2.8 on 2025-11-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionset_created_at_questionset_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('required_skills', models.JSONField(default=list)),
                ('salary_range', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-posted_date', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('skills', models.JSONField(default=list)),
                ('preferred_job_titles', models.JSONField(default=list)),
                ('preferred_locations', models.JSONField(default=list)),
                ('cv_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.joboffer')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('user_profile', 'job_offer')},
            },
        ),
    ]
