# Generated by Django 4.2.25 on 2025-10-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatchresult',
            name='evidence',
            field=models.JSONField(default=list),
        ),
    ]
