# Generated by Django 4.2.25 on 2025-10-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skillmatchresult_evidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scoreresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='created_at',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillmatchresult',
            name='cv_skill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmatchresult',
            name='jd_skill_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillmatchresult',
            name='match_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
