# Generated by Django 4.2.25 on 2025-10-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_interviewsession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreresult',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillmatchresult',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
