# Generated by Django 4.2.25 on 2025-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_questionset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='questions',
            field=models.JSONField(),
        ),
    ]
