# Generated by Django 5.2 on 2025-10-25 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_gen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
