# Generated by Django 4.2.26 on 2025-11-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobdispatchlog',
            new_name='jobs_jobdis_user_id_a66b8a_idx',
            old_name='jobs_jobdis_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='jobs_jobpos_publish_15cb5b_idx',
            old_name='jobs_jobpos_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='jobs_jobpos_remote_032c29_idx',
            old_name='jobs_jobpos_remote_idx',
        ),
    ]
